stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - echo "another:$CI_COMMIT_SHA/$CI_COMMIT_TITLE"

print_second:
  stage: second
  tags:
    - build
  only:
    - develop
  script:
    - echo "app:$CI_REGISTRY_USER/$CI_REGISTRY/$CI_RUNNER_TAGS"

print_third:
  stage: third
  tags:
    - build
  only:
    - develop
  script:
    - echo $APP_NAME
    - echo $APP_ENV
    - echo $APP_KEY
    - echo $APP_DEBUG
    - echo $APP_URL
    - echo $DB_CONNECTION
    - echo $DB_HOST
    - echo $DB_PORT
    - echo $DB_DATABASE
    - echo $DB_USERNAME