stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script: echo "hello world first!"

print_second:
  stage: second
  tags:
    - build
  only:
    - develop
  script: echo "hello world second!"


print_third:
  stage: third
  tags:
    - build
  only:
    - develop
  script: echo "hello world third!"