stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - echo "another:$CI_COMMIT_SHA/$CI_COMMIT_TITLE"

print_second:
  stage: second
  tags:
    - build
  only:
    - develop
  script:
    - echo "app:$CI_REGISTRY_USER/$CI_REGISTRY/$CI_RUNNER_TAGS"

print_third:
  stage: third
  tags:
    - build
  only:
    - develop
  script: echo "hello world third!"